name: hospitals
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  rxdart: any
  random_color: ^1.0.3
  floor: ^0.11.0
  flutter_bloc: any
  equatable: ^1.1.1
  http: ^0.12.0
  image_picker: any
  path_provider: any
  built_value: ^7.0.9
  transparent_image: ^1.0.0
  cached_network_image: ^2.0.0
  flutter_spinkit: "^2.1.0"
  photo_view: ^0.9.2
  gesture_x_detector: ^0.0.5
  after_init: ^0.1.2
  rect_getter: ^0.1.0
  async: any
  # fullscreen: ^1.0.1
  animated_image_list: ^0.5.2
  image: ^2.1.19
  vector_math: ^2.0.8
  peek_and_pop: any
  # flutter_ffmpeg: ^0.3.1
  flutter_stage: ^0.0.1
  animated_rail: ^1.0.0
  beamer: ^0.6.4+1
  provider: ^5.0.0
  background_locator: ^1.5.0+1
  location_permissions: ^3.0.0+1
  flutter_plugin_android_lifecycle: ^2.0.1

analyzer:
  enable-experiment:
    - spread-collections

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.3
  built_value_generator: ^7.0.9
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  assets:
    - assets/separator.png
    - assets/IronMan.obj
    - assets/file.obj
    - assets/placeholder.png
    

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
