import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedPhotosGrid {
  final List<PhotosGridModel> results;

  AutogeneratedPhotosGrid({this.results});

  factory AutogeneratedPhotosGrid.fromJson(Map<String, dynamic> json) {
    List<PhotosGridModel> temp;
    if (json['results'] != null) {
      temp = <PhotosGridModel>[];
      json['results'].forEach((v) {
        temp.add(PhotosGridModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedPhotosGrid(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class PhotosGridModel extends Equatable {
  final int id;
  final String name;

  PhotosGridModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory PhotosGridModel.fromJson(Map<String, dynamic> json) {
    return PhotosGridModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
  
}
